version: "3.3"

services:

  test-server:
    build:
      context: .
    image: test-server
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    networks:
      - internal
    restart: always

  mongodb:
    image: mongo
    ports: 
      - 27017:27017
    networks:
      - internal

networks:
  internal:
